services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Ilikeminecraft040610
      MYSQL_DATABASE: reservation_system
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./API/Mysql/code.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  api:
    build: ./API
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    env_file:
      - ./API/.env
    depends_on:
      - mysql
    restart: unless-stopped
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  flutter-dev:
    build:
      context: ./ticket_com
      dockerfile: Dockerfile.dev
    container_name: flutter_dev
    volumes:
      - ./ticket_com:/app
    working_dir: /app
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8081 --dart-define=API_BASE_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  mysql_data:
