-- Fresh PostgreSQL / Supabase schema for the API reservation system.
-- Run in an empty schema (normally public). Safe to re-run for tables/indexes and
-- reference seeds; this is NOT an upgrade script for a partially migrated MySQL DB.
-- No accounts, orders, events, personal data, sponsors, or user categories are seeded.
-- Identifiers deliberately use unquoted lowercase: PostgreSQL folds API's unquoted
-- CamelCase SQL identifiers to lowercase. Integer flags are SMALLINT, not BOOLEAN,
-- because the API writes 0/1 and compares flags to numeric 1.
-- MySQL DATETIME is represented by TIMESTAMP WITHOUT TIME ZONE; the application
-- must use a consistent timezone (preferably UTC) when writing timestamps.

BEGIN;

-- Fixed references and role/permission catalog.
CREATE TABLE IF NOT EXISTS accountstatusinfo (
    statusid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statustype VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventstatusinfo (
    eventstatusid INTEGER PRIMARY KEY,
    statusname VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS organizerstatusinfo (
    organizerstatusid INTEGER PRIMARY KEY,
    statusname VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventquestiontype (
    eventquestiontypeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventquestiontype VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventrole (
    eventroleid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolename VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS teamrole (
    teamroleid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teamrolename VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS memberstatusinfo (
    memberstatusid INTEGER PRIMARY KEY,
    statusname VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS paymenttypeinfo (
    paymenttypeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paymenttypename VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS verificationstatusinfo (
    verificationstatusid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statusname VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS verificationtypeinfo (
    verificationtypeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idtype VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS permissioninfo (
    permissionid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permissionname VARCHAR(100) NOT NULL UNIQUE,
    permissiondescription VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS rolepermissioninfo (
    rolepermissionid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statusid INTEGER NOT NULL REFERENCES accountstatusinfo(statusid) ON DELETE CASCADE,
    permissionid INTEGER NOT NULL REFERENCES permissioninfo(permissionid) ON DELETE CASCADE,
    CONSTRAINT uq_status_permission UNIQUE (statusid, permissionid)
);

-- Accounts, organizations, categories, events.
CREATE TABLE IF NOT EXISTS accountinfo (
    accountid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    phonenum VARCHAR(20) NOT NULL,
    profileimagepath VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    statusid INTEGER NOT NULL REFERENCES accountstatusinfo(statusid),
    passwordenc VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categoryinfo (
    categoryid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryname VARCHAR(50) NOT NULL,
    categoryiconpath VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventorganizerinfo (
    eventorganizerid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventorganizername VARCHAR(255) NOT NULL,
    eventorganizerlogopath VARCHAR(255) NOT NULL,
    createdbyaccountid INTEGER NOT NULL REFERENCES accountinfo(accountid),
    -- The API inserts NULL for optional descriptions.
    eventorganizerdiscription TEXT,
    -- Application flow: 1 pending, 2 approved, 3 denied.
    organizerstatusid INTEGER NOT NULL DEFAULT 1 REFERENCES organizerstatusinfo(organizerstatusid)
);

CREATE TABLE IF NOT EXISTS eventinfo (
    eventid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventname VARCHAR(100) NOT NULL,
    eventstartingymdt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    eventendingymdt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    eventaddress VARCHAR(255) NOT NULL,
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    eventdescription TEXT NOT NULL,
    eventorganizerid INTEGER NOT NULL REFERENCES eventorganizerinfo(eventorganizerid),
    oneperperson SMALLINT NOT NULL DEFAULT 0 CHECK (oneperperson IN (0, 1)),
    -- Original dump defaulted to Approved; the API explicitly sets Pending
    -- on non-admin creations. Keep that default for legacy INSERT callers.
    eventstatusid INTEGER NOT NULL DEFAULT 2 REFERENCES eventstatusinfo(eventstatusid),
    eventvisible SMALLINT NOT NULL DEFAULT 1 CHECK (eventvisible IN (0, 1)),
    -- Used by the current team dashboard, though absent in the MySQL dump.
    scanenabled SMALLINT NOT NULL DEFAULT 0 CHECK (scanenabled IN (0, 1))
);

CREATE TABLE IF NOT EXISTS organizermember (
    memberid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid),
    eventorganizerid INTEGER NOT NULL REFERENCES eventorganizerinfo(eventorganizerid) ON DELETE CASCADE,
    teamroleid INTEGER NOT NULL REFERENCES teamrole(teamroleid),
    -- Old members were backfilled Active in the invite migration.
    memberstatusid INTEGER NOT NULL DEFAULT 2 REFERENCES memberstatusinfo(memberstatusid)
);

-- Equivalent to the MySQL generated ActiveMembershipKey unique index: there
-- may be many removed (status 4) rows, but only one live invitation/membership.
CREATE UNIQUE INDEX IF NOT EXISTS uq_organizer_active_member
    ON organizermember (accountid, eventorganizerid) WHERE memberstatusid <> 4;

CREATE TABLE IF NOT EXISTS eventstaff (
    -- Preserve the typo in the MySQL/API column name, not "assignmentid".
    assigmentid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    memberid INTEGER NOT NULL REFERENCES organizermember(memberid),
    eventroleid INTEGER NOT NULL REFERENCES eventrole(eventroleid),
    assignedatymdt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canscan SMALLINT NOT NULL DEFAULT 0 CHECK (canscan IN (0, 1)),
    CONSTRAINT uq_event_staff_member UNIQUE (eventid, memberid)
);

CREATE TABLE IF NOT EXISTS eventcategoryinfo (
    eventcategoryid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    categoryid INTEGER NOT NULL REFERENCES categoryinfo(categoryid)
);

CREATE TABLE IF NOT EXISTS eventimageinfo (
    imageid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    imagename VARCHAR(50) NOT NULL,
    imagepath VARCHAR(255) NOT NULL,
    isthumbnail SMALLINT NOT NULL DEFAULT 0 CHECK (isthumbnail IN (0, 1))
);

CREATE TABLE IF NOT EXISTS eventquestioninfo (
    eventquestionid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    eventquestion VARCHAR(255) NOT NULL,
    eventquestiontypeid INTEGER NOT NULL REFERENCES eventquestiontype(eventquestiontypeid),
    -- The API binds a Python bool directly for this field (unlike its other 0/1 flags).
    isrequire BOOLEAN NOT NULL,
    sortorder INTEGER NOT NULL,
    -- API json.dumps/json.loads expects a string rather than a decoded JSONB.
    options TEXT
);

CREATE TABLE IF NOT EXISTS sponserinfo (
    sponserid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sponsername VARCHAR(50) NOT NULL,
    sponserlogopath VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventsponserinfo (
    eventsponserid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    sponserid INTEGER NOT NULL REFERENCES sponserinfo(sponserid)
);

CREATE TABLE IF NOT EXISTS tickettype (
    tickettypeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    typename VARCHAR(45) NOT NULL,
    priceinkip INTEGER NOT NULL,
    capacity INTEGER NOT NULL,
    salestartymdt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    saleendymdt TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ordersinfo (
    orderid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid),
    paymenttypeid INTEGER REFERENCES paymenttypeinfo(paymenttypeid),
    -- The API can send NULL explicitly, even for free tickets.
    paymentdateymdt TIMESTAMP WITHOUT TIME ZONE,
    proveofpayment VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ticketattendence (
    attendeeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tickettypeid INTEGER NOT NULL REFERENCES tickettype(tickettypeid),
    orderid INTEGER NOT NULL REFERENCES ordersinfo(orderid) ON DELETE CASCADE,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    phonenum VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nationalid VARCHAR(50),
    isvalid SMALLINT NOT NULL DEFAULT 1 CHECK (isvalid IN (0, 1))
);

CREATE TABLE IF NOT EXISTS attendeeresponse (
    responseid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventquestionid INTEGER NOT NULL REFERENCES eventquestioninfo(eventquestionid) ON DELETE CASCADE,
    attendeeid INTEGER NOT NULL REFERENCES ticketattendence(attendeeid) ON DELETE CASCADE,
    attendeeanswer VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticketcheckin (
    checkinid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendeeid INTEGER NOT NULL REFERENCES ticketattendence(attendeeid) ON DELETE CASCADE,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    checkedinbymemberid INTEGER NOT NULL REFERENCES organizermember(memberid),
    checkedinatymdt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendee_event UNIQUE (attendeeid, eventid)
);

CREATE TABLE IF NOT EXISTS identityverification (
    verificationid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid),
    verificationtypeid INTEGER NOT NULL REFERENCES verificationtypeinfo(verificationtypeid),
    idnumberencrypted VARCHAR(255) NOT NULL,
    fullnameonid VARCHAR(255) NOT NULL,
    -- Optional in models/schema.py and sent as NULL by the API.
    dateofbirth DATE,
    documentimageredpath VARCHAR(255),
    verificationstatusid INTEGER NOT NULL REFERENCES verificationstatusinfo(verificationstatusid),
    reviewedbyaccountid INTEGER REFERENCES accountinfo(accountid),
    submittedatymdt TIMESTAMP WITHOUT TIME ZONE,
    reviewedatymdt TIMESTAMP WITHOUT TIME ZONE
);

-- Personalization/notifications (from create_missing_tables.sql and invite flow).
CREATE TABLE IF NOT EXISTS accountcategoryinfo (
    accountcategoryid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid) ON DELETE CASCADE,
    categoryid INTEGER NOT NULL REFERENCES categoryinfo(categoryid) ON DELETE CASCADE,
    createdatymdt TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_account_category UNIQUE (accountid, categoryid)
);

CREATE TABLE IF NOT EXISTS wishlistinfo (
    wishid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid) ON DELETE CASCADE,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    createdatymdt TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_account_event UNIQUE (accountid, eventid)
);

CREATE TABLE IF NOT EXISTS followinfo (
    followid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid) ON DELETE CASCADE,
    eventorganizerid INTEGER NOT NULL REFERENCES eventorganizerinfo(eventorganizerid) ON DELETE CASCADE,
    createdatymdt TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_account_organizer UNIQUE (accountid, eventorganizerid)
);

CREATE TABLE IF NOT EXISTS eventviewinfo (
    viewid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid) ON DELETE CASCADE,
    eventid INTEGER NOT NULL REFERENCES eventinfo(eventid) ON DELETE CASCADE,
    viewedatymdt TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificationinfo (
    notificationid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid INTEGER NOT NULL REFERENCES accountinfo(accountid) ON DELETE CASCADE,
    notificationtype VARCHAR(30) NOT NULL DEFAULT 'system',
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    link VARCHAR(255),
    isread SMALLINT NOT NULL DEFAULT 0 CHECK (isread IN (0, 1)),
    createdatymdt TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Foreign-key access paths (PostgreSQL does not create indexes for referencing
-- columns automatically). PK/UNIQUE indexes above cover their own leftmost keys.
CREATE INDEX IF NOT EXISTS idx_accountinfo_status ON accountinfo(statusid);
CREATE INDEX IF NOT EXISTS idx_accountinfo_email_lower ON accountinfo (lower(email));
CREATE INDEX IF NOT EXISTS idx_rolepermission_permission ON rolepermissioninfo(permissionid);
CREATE INDEX IF NOT EXISTS idx_eventorganizer_owner ON eventorganizerinfo(createdbyaccountid);
CREATE INDEX IF NOT EXISTS idx_eventinfo_organizer ON eventinfo(eventorganizerid);
CREATE INDEX IF NOT EXISTS idx_eventinfo_public ON eventinfo(eventstartingymdt)
    WHERE eventstatusid = 2 AND eventvisible = 1;
CREATE INDEX IF NOT EXISTS idx_member_org ON organizermember(eventorganizerid);
CREATE INDEX IF NOT EXISTS idx_member_account_status ON organizermember(accountid, memberstatusid);
CREATE INDEX IF NOT EXISTS idx_member_role ON organizermember(teamroleid);
CREATE INDEX IF NOT EXISTS idx_eventstaff_member ON eventstaff(memberid);
CREATE INDEX IF NOT EXISTS idx_eventstaff_role ON eventstaff(eventroleid);
CREATE INDEX IF NOT EXISTS idx_eventcategory_event ON eventcategoryinfo(eventid);
CREATE INDEX IF NOT EXISTS idx_eventcategory_category ON eventcategoryinfo(categoryid);
CREATE INDEX IF NOT EXISTS idx_eventimage_event ON eventimageinfo(eventid);
CREATE INDEX IF NOT EXISTS idx_eventquestion_event_sort ON eventquestioninfo(eventid, sortorder);
CREATE INDEX IF NOT EXISTS idx_eventquestion_type ON eventquestioninfo(eventquestiontypeid);
CREATE INDEX IF NOT EXISTS idx_eventsponser_event ON eventsponserinfo(eventid);
CREATE INDEX IF NOT EXISTS idx_eventsponser_sponser ON eventsponserinfo(sponserid);
CREATE INDEX IF NOT EXISTS idx_tickettype_event ON tickettype(eventid);
CREATE INDEX IF NOT EXISTS idx_orders_account ON ordersinfo(accountid);
CREATE INDEX IF NOT EXISTS idx_orders_paymenttype ON ordersinfo(paymenttypeid);
CREATE INDEX IF NOT EXISTS idx_attendee_tickettype ON ticketattendence(tickettypeid);
CREATE INDEX IF NOT EXISTS idx_attendee_order ON ticketattendence(orderid);
CREATE INDEX IF NOT EXISTS idx_response_question ON attendeeresponse(eventquestionid);
CREATE INDEX IF NOT EXISTS idx_response_attendee ON attendeeresponse(attendeeid);
CREATE INDEX IF NOT EXISTS idx_checkin_event ON ticketcheckin(eventid);
CREATE INDEX IF NOT EXISTS idx_checkin_member ON ticketcheckin(checkedinbymemberid);
CREATE INDEX IF NOT EXISTS idx_verification_account ON identityverification(accountid);
CREATE INDEX IF NOT EXISTS idx_verification_type ON identityverification(verificationtypeid);
CREATE INDEX IF NOT EXISTS idx_verification_status ON identityverification(verificationstatusid);
CREATE INDEX IF NOT EXISTS idx_verification_reviewer ON identityverification(reviewedbyaccountid);
CREATE INDEX IF NOT EXISTS idx_accountcategory_category ON accountcategoryinfo(categoryid);
CREATE INDEX IF NOT EXISTS idx_wishlist_event ON wishlistinfo(eventid);
CREATE INDEX IF NOT EXISTS idx_follow_organizer ON followinfo(eventorganizerid);
CREATE INDEX IF NOT EXISTS idx_eventview_account ON eventviewinfo(accountid);
CREATE INDEX IF NOT EXISTS idx_eventview_event ON eventviewinfo(eventid);
CREATE INDEX IF NOT EXISTS idx_notification_account_date ON notificationinfo(accountid, createdatymdt DESC);

-- Reference data only. Use stable numeric IDs where application logic requires
-- them. No bootstrap administrator is created; provision that account separately.
INSERT INTO accountstatusinfo (statusid, statustype) VALUES
    (1, 'CUSTOMER'), (2, 'ORGANIZER'), (3, 'SUPERADMIN'),
    (4, 'EMPLOYEE'), (5, 'Ban')
ON CONFLICT (statusid) DO UPDATE SET statustype = EXCLUDED.statustype;
INSERT INTO eventstatusinfo (eventstatusid, statusname) VALUES
    (1, 'Pending'), (2, 'Approved'), (3, 'Denied')
ON CONFLICT (eventstatusid) DO UPDATE SET statusname = EXCLUDED.statusname;
INSERT INTO organizerstatusinfo (organizerstatusid, statusname) VALUES
    (1, 'Pending'), (2, 'Approved'), (3, 'Denied')
ON CONFLICT (organizerstatusid) DO UPDATE SET statusname = EXCLUDED.statusname;
INSERT INTO eventquestiontype (eventquestiontypeid, eventquestiontype) VALUES
    (1, 'Text'), (2, 'Checkbox'), (3, 'Radio box'),
    (4, 'Text save as encrypted'), (5, 'Yes or No')
ON CONFLICT (eventquestiontypeid) DO UPDATE SET eventquestiontype = EXCLUDED.eventquestiontype;
INSERT INTO eventrole (eventroleid, rolename) VALUES
    (1, 'Editor'), (2, 'Viewer2')
ON CONFLICT (eventroleid) DO UPDATE SET rolename = EXCLUDED.rolename;
INSERT INTO teamrole (teamroleid, teamrolename) VALUES
    (1, 'Staff / Employee'), (2, 'Volunteer'), (3, 'Page Designer'),
    (4, 'Org Admin'), (5, 'Org Owner')
ON CONFLICT (teamroleid) DO UPDATE SET teamrolename = EXCLUDED.teamrolename;
INSERT INTO memberstatusinfo (memberstatusid, statusname) VALUES
    (1, 'Pending'), (2, 'Active'), (3, 'Declined'), (4, 'Removed')
ON CONFLICT (memberstatusid) DO UPDATE SET statusname = EXCLUDED.statusname;
INSERT INTO paymenttypeinfo (paymenttypeid, paymenttypename) VALUES
    (1, 'BCEL'), (2, 'APB'), (3, 'LDB')
ON CONFLICT (paymenttypeid) DO UPDATE SET paymenttypename = EXCLUDED.paymenttypename;
INSERT INTO verificationstatusinfo (verificationstatusid, statusname) VALUES
    (1, 'Pending'), (2, 'Approved'), (3, 'Denied')
ON CONFLICT (verificationstatusid) DO UPDATE SET statusname = EXCLUDED.statusname;
INSERT INTO verificationtypeinfo (verificationtypeid, idtype) VALUES
    (1, 'Password'), (2, 'Personal Residency Card ID'), (5, 'My Number Card')
ON CONFLICT (verificationtypeid) DO UPDATE SET idtype = EXCLUDED.idtype;

INSERT INTO permissioninfo (permissionname, permissiondescription) VALUES
    ('view_events', 'View events list and details'),
    ('create_event', 'Create new events'),
    ('update_event', 'Update existing events'),
    ('delete_event', 'Delete events'),
    ('manage_event_organizer', 'Create/update/delete event organizers'),
    ('manage_event_members', 'Create/update/delete organizer members'),
    ('manage_categories', 'Create/update/delete categories and event-category links'),
    ('manage_event_images', 'Upload/replace/delete event images'),
    ('manage_ticket_types', 'Create/update/delete ticket types'),
    ('manage_event_questions', 'Create/update/delete event questions'),
    ('manage_accounts', 'Create/update/delete accounts'),
    ('manage_orders', 'View/manage orders'),
    ('manage_wishlist', 'Add/remove wishlist items'),
    ('manage_identity_verifications', 'Approve/deny identity verification and grant organizer access')
ON CONFLICT (permissionname) DO UPDATE SET permissiondescription = EXCLUDED.permissiondescription;

INSERT INTO rolepermissioninfo (statusid, permissionid)
SELECT r.statusid, p.permissionid
FROM (VALUES
    (1, 'view_events'), (1, 'manage_wishlist'),
    (2, 'view_events'), (2, 'create_event'), (2, 'update_event'),
    (2, 'manage_event_organizer'), (2, 'manage_event_members'),
    (2, 'manage_event_images'), (2, 'manage_categories'),
    (2, 'manage_ticket_types'), (2, 'manage_event_questions'),
    (2, 'manage_orders'), (2, 'manage_wishlist'),
    (4, 'manage_identity_verifications')
) AS r(statusid, permissionname)
JOIN permissioninfo p ON p.permissionname = r.permissionname
ON CONFLICT (statusid, permissionid) DO NOTHING;
INSERT INTO rolepermissioninfo (statusid, permissionid)
SELECT 3, permissionid FROM permissioninfo
ON CONFLICT (statusid, permissionid) DO NOTHING;

-- Explicit identity values in seed INSERTs do not advance PostgreSQL sequences.
-- GREATEST keeps a sequence from going backwards if the script is re-run
-- after a high-ID lookup entry was created and later deleted.
SELECT setval(pg_get_serial_sequence('accountstatusinfo', 'statusid'),
    GREATEST((SELECT max(statusid) FROM accountstatusinfo),
             (SELECT last_value FROM accountstatusinfo_statusid_seq)), true);
SELECT setval(pg_get_serial_sequence('eventquestiontype', 'eventquestiontypeid'),
    GREATEST((SELECT max(eventquestiontypeid) FROM eventquestiontype),
             (SELECT last_value FROM eventquestiontype_eventquestiontypeid_seq)), true);
SELECT setval(pg_get_serial_sequence('eventrole', 'eventroleid'),
    GREATEST((SELECT max(eventroleid) FROM eventrole),
             (SELECT last_value FROM eventrole_eventroleid_seq)), true);
SELECT setval(pg_get_serial_sequence('teamrole', 'teamroleid'),
    GREATEST((SELECT max(teamroleid) FROM teamrole),
             (SELECT last_value FROM teamrole_teamroleid_seq)), true);
SELECT setval(pg_get_serial_sequence('paymenttypeinfo', 'paymenttypeid'),
    GREATEST((SELECT max(paymenttypeid) FROM paymenttypeinfo),
             (SELECT last_value FROM paymenttypeinfo_paymenttypeid_seq)), true);
SELECT setval(pg_get_serial_sequence('verificationstatusinfo', 'verificationstatusid'),
    GREATEST((SELECT max(verificationstatusid) FROM verificationstatusinfo),
             (SELECT last_value FROM verificationstatusinfo_verificationstatusid_seq)), true);
SELECT setval(pg_get_serial_sequence('verificationtypeinfo', 'verificationtypeid'),
    GREATEST((SELECT max(verificationtypeid) FROM verificationtypeinfo),
             (SELECT last_value FROM verificationtypeinfo_verificationtypeid_seq)), true);

COMMIT;
